// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kctcbdssehmsknuxfdsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjdGNiZHNzZWhtc2tudXhmZHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwODg2NjMsImV4cCI6MjA1MTY2NDY2M30.oc9s6M0Chse6zyVhHRQZwUTCuCIKMWxj3VaM4oSTf1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);